name: Run Postman API Tests 

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout ⚙️
        uses: actions/checkout@v4

      - name: Setup Node (for Newman)
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install Newman + HTML reporter
        run: npm i -g newman newman-reporter-htmlextra          

      - name: Start containers 🐳
        run: |
          export DISABLE_LOGGING=true
          docker compose -f docker-compose.yml up -d --force-recreate

      - name: Sleep for 60 seconds
        run: sleep 60s
        shell: bash

      - name: Create & Seed database 🌱
        run: |
          docker compose exec -T laravel-api php artisan migrate:refresh --seed
      - name: Newman - Create new product
        run: |
          mkdir -p newman
          newman run postman/collections/HW07.postman_collection.json \
            --folder "Search product" \
            --iteration-data postman/data/addProductData.csv \
            --reporters cli,htmlextra \
      	    --reporter-htmlextra-export "reports/search_product.html"

      - name: Cleanup containers
        if: always()
        run: docker compose down -v