name: Run Postman API Tests 

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout ⚙️
        uses: actions/checkout@v4
      - name: Start containers 🐳
        run: |
          export DISABLE_LOGGING=true
          docker compose up -d --force-recreate
      - name: Wait for API ready
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:8091/status; then
              echo "API is ready"
              exit 0
            fi
            echo "Waiting for API..."
            sleep 5
          done
          exit 1
      - name: Install node ⚙️
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Newman + HTML reporter
        run: npm i -g newman newman-reporter-htmlextra
      - name: Create & Seed database 🌱
        run: |
          docker compose exec -T laravel-api php artisan migrate:refresh --seed
      - name: Debug Search Product
        run: curl -v -X POST "http://localhost:8091/products/search?q=hammer"
      - name: Newman - Create new product
        run: |
          mkdir -p newman
          newman run postman/collections/HW07.postman_collection.json \
            --folder "Search product" \
            --iteration-data postman/data/searchProductData.csv \
            --reporters cli,htmlextra \
            --reporter-htmlextra-export newman/report-search-product.html
      - name: Create & Seed database 🌱
        run: |
          docker compose exec -T laravel-api php artisan migrate:refresh --seed
      - name: Newman - Create Invoice
        run: |
          newman run postman/collections/HW07.postman_collection.json \
            --folder "Create Invoice" \
            --iteration-data postman/data/createInvoiceData.csv \
            --reporters cli,htmlextra \
            --reporter-htmlextra-export newman/report-create-invoice.html
      - name: Create & Seed database 🌱
        run: |
          docker compose exec -T laravel-api php artisan migrate:refresh --seed
      - name: Newman - Change Password
        run: |
          newman run postman/collections/HW07.postman_collection.json \
            --folder "Change password" \
            --iteration-data postman/data/changePasswordData.csv \
            --reporters cli,htmlextra \
            --reporter-htmlextra-export newman/report-change-password.html
      - name: Cleanup containers
        if: always()
        run: docker compose down -v